# Generated by Django 4.0 on 2023-06-28 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_alter_profile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('spot', models.CharField(max_length=300)),
                ('date', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('facebook', models.CharField(blank=True, max_length=350, null=True)),
                ('instagram', models.CharField(blank=True, max_length=350, null=True)),
                ('ticket', models.CharField(blank=True, max_length=350, null=True)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
