# Generated by Django 4.0 on 2023-06-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='host_phone_number',
            field=models.CharField(default=9876543210, max_length=10),
            preserve_default=False,
        ),
    ]
