# Generated by Django 4.0 on 2023-07-02 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_alter_profile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('image_url', models.CharField(max_length=500)),
                ('source', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('feed_type', models.CharField(choices=[('D', 'Discover'), ('E', 'Event'), ('U', 'Untold'), ('F', 'Feed')], max_length=1)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
    ]
