# Generated by Django 4.0 on 2023-07-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_alter_feed_feed_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='related_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
