# Generated by Django 4.0 on 2023-07-09 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_feed_related_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='related_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
