# Generated by Django 4.0 on 2023-07-03 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0004_discovereditorchoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discovereditorchoice',
            name='feed_item',
        ),
    ]
