# Generated by Django 4.0 on 2023-07-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0005_remove_discovereditorchoice_feed_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='discover',
            name='logo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
